---
title: "Aaron Rodgers Analysis"
author: "Myles Thomas"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#remotes::install_github("jthomasmock/espnscrapeR")
library(tidyverse)
library(dplyr)
library(tictoc)
library(espnscrapeR)
library(tidyverse)
library(ggtext)
library(adegenet)
library(ggplot2)
library(ggimage)
library(extrafont)
#loadfonts(device = "win")
library(scales)
library(ggthemes)
```




```{r grab tables from espn}
# scraping 2020 qbr table
library(rvest)

url <- "https://www.espn.com/nfl/qbr/_/season/2020/seasontype/2"
#url <- "https://www.espn.com/nfl/qbr"

webpage <- read_html(url)

tbls <- html_nodes(webpage, "table")

head(tbls)


# tables
tables <- webpage %>%
        html_nodes("table") %>%
        .[1:2] %>%
        html_table(fill = TRUE)

# cbind tables
data2020 <- cbind(tables[[1]], tables[[2]]) ; data2020



# 2019 qbr
url <- "https://www.espn.com/nfl/qbr/_/season/2019/seasontype/2"

webpage <- read_html(url)

tbls <- html_nodes(webpage, "table")

head(tbls)


# tables
tables <- webpage %>%
        html_nodes("table") %>%
        .[1:2] %>%
        html_table(fill = TRUE)

# cbind tables
data2019 <- cbind(tables[[1]], tables[[2]]) ; data2019



# 2018 qbr
url <- "https://www.espn.com/nfl/qbr/_/season/2018/seasontype/2"

webpage <- read_html(url)

tbls <- html_nodes(webpage, "table")

head(tbls)


# tables
tables <- webpage %>%
        html_nodes("table") %>%
        .[1:2] %>%
        html_table(fill = TRUE)

# cbind tables
data2018 <- cbind(tables[[1]], tables[[2]]) ; data2018



# 2017 qbr
url <- "https://www.espn.com/nfl/qbr/_/season/2017/seasontype/2"

webpage <- read_html(url)

tbls <- html_nodes(webpage, "table")

head(tbls)


# tables
tables <- webpage %>%
        html_nodes("table") %>%
        .[1:2] %>%
        html_table(fill = TRUE)

# cbind tables
data2017 <- cbind(tables[[1]], tables[[2]]) ; data2017




# 2016 qbr
url <- "https://www.espn.com/nfl/qbr/_/season/2016/seasontype/2"

webpage <- read_html(url)

tbls <- html_nodes(webpage, "table")

head(tbls)


# tables
tables <- webpage %>%
        html_nodes("table") %>%
        .[1:2] %>%
        html_table(fill = TRUE)

# cbind tables
data2016 <- cbind(tables[[1]], tables[[2]]) ; data2016




# 2015 qbr
url <- "https://www.espn.com/nfl/qbr/_/season/2015/seasontype/2"

webpage <- read_html(url)

tbls <- html_nodes(webpage, "table")

head(tbls)


# tables
tables <- webpage %>%
        html_nodes("table") %>%
        .[1:2] %>%
        html_table(fill = TRUE)

# cbind tables
data2015 <- cbind(tables[[1]], tables[[2]]) ; data2015
```


```{r add binary for who made playoffs}
# 2015
data2015$playoffs <- ifelse(
         data2015$Name == data2015$Name[1] | # palmer
         data2015$Name == data2015$Name[2] | # big ben
         data2015$Name == data2015$Name[3] | # dalton
         data2015$Name == data2015$Name[4] | # russ
         data2015$Name == data2015$Name[5] | # brady
         data2015$Name == data2015$Name[6] | # kirk
         data2015$Name == data2015$Name[11] | # cam newton
         data2015$Name == data2015$Name[12] | # alex smith
         data2015$Name == data2015$Name[22] | # brian hoyer
         data2015$Name == data2015$Name[17] | # teddy bridge
         data2015$Name == data2015$Name[28] | # manning
         data2015$Name == data2015$Name[14], # rodgers
         1, 0)

# 2016
data2016$playoffs <- ifelse(
  data2016$Name == data2016$Name[1] | # matt ryan
    data2016$Name == data2016$Name[2] | # tom brady 
    data2016$Name == data2016$Name[3] | # dak
    data2016$Name == data2016$Name[4] | # rodgers
    data2016$Name == data2016$Name[27] | # eli
    data2016$Name == data2016$Name[15] | # russ
    data2016$Name == data2016$Name[8] | # stafford
    data2016$Name == data2016$Name[10] | # alex smith
    data2016$Name == data2016$Name[11] | # big ben
    data2016$Name == data2016$Name[22] | # osweiler
    data2016$Name == data2016$Name[16] | # derek carr 
    data2016$Name == data2016$Name[24], # tannehill
    1, 0)

# 2017
data2017$playoffs <- ifelse(
  data2017$Name == data2017$Name[1] | # wentz
    data2017$Name == data2017$Name[2] | # keenum
    data2017$Name == data2017$Name[16] | # goff
    data2017$Name == data2017$Name[9] | # brees
    data2017$Name == data2017$Name[19] | # newton
    data2017$Name == data2017$Name[5] | # matt ryan
    data2017$Name == data2017$Name[3] | # brady
    data2017$Name == data2017$Name[6] | # big ben
    data2017$Name == data2017$Name[12] | # bortles
    data2017$Name == data2017$Name[8] | # alex smith
    data2017$Name == data2017$Name[13] | # mariota
    data2017$Name == data2017$Name[14], # tyrod
    1, 0)

# 2018
data2018$playoffs <- ifelse(
  data2018$Name == data2018$Name[1] | # mahomes
    data2018$Name == data2018$Name[6] | # brady
    data2018$Name == data2018$Name[13] | # deshaun watson
    data2018$Name == data2018$Name[12] | # wentz
    data2018$Name == data2018$Name[7] | # phil rivers
    data2018$Name == data2018$Name[18] | # flacco
    data2018$Name == data2018$Name[5] | # luck 
    data2018$Name == data2018$Name[2] | # brees
    data2018$Name == data2018$Name[10] | # goff
    data2018$Name == data2018$Name[3] | # trubisky
    data2018$Name == data2018$Name[17] | # dak
    data2018$Name == data2018$Name[11],  # russ
  1, 0)

# 2019
data2019$playoffs <- ifelse(
  data2019$Name == data2019$Name[1] | # lamar
    data2019$Name == data2019$Name[2] | # mahomes
    data2019$Name == data2019$Name[12] | # jimmy g
    data2019$Name == data2019$Name[7] | # deshaun
    data2019$Name == data2019$Name[24] | # josh allen 
    data2019$Name == data2019$Name[9] | # tannehill 
    data2019$Name == data2019$Name[17] | # brady
    data2019$Name == data2019$Name[20] | # rodgers
    data2019$Name == data2019$Name[3] | # brees
    data2019$Name == data2019$Name[11] | # wentz
    data2019$Name == data2019$Name[5] | # russ
    data2019$Name == data2019$Name[13], # cousins
  1, 0)

# 2020
data2020$playoffs <- ifelse(
  data2020$Name == data2020$Name[1] | # rodgers
    data2020$Name == data2020$Name[2] | # mahomes
    data2020$Name == data2020$Name[3] | # josh allen
    data2020$Name == data2020$Name[4] | # tannehill
    data2020$Name == data2020$Name[6] | # brees
    data2020$Name == data2020$Name[7] | # lamar
    data2020$Name == data2020$Name[8] | # russ
    data2020$Name == data2020$Name[9] | # brady
    data2020$Name == data2020$Name[10] | # baker 
    data2020$Name == data2020$Name[21] | # trubisky
    data2020$Name == data2020$Name[22] | # big ben
    data2020$Name == data2020$Name[23] | # goff
    # washington had no QB qualify
    data2020$Name == data2020$Name[19], # phil rivers
    1, 0)

```



```{r create subsets with only playoff QBs}
subset2015 <- data2015 %>%
  filter(playoffs == 1)

subset2016 <- data2016 %>%
  filter(playoffs == 1)

subset2017 <- data2017 %>%
  filter(playoffs == 1)

subset2018 <- data2018 %>%
  filter(playoffs == 1)

subset2019 <- data2019 %>%
  filter(playoffs == 1)

subset2020 <- data2020 %>%
  filter(playoffs == 1)
```


```{r create vector of means}
playoffs_qb_mean <- c(
subset2015$QBR %>% mean,
subset2016$QBR %>% mean,
subset2017$QBR %>% mean,
subset2018$QBR %>% mean,
subset2019$QBR %>% mean,
subset2020$QBR %>% mean
)
```



```{r grab vector rodgers for all 6 years}
rodgers_vector <- c(
data2015[data2015$Name=="Aaron Rodgers", ]$QBR,
data2016[data2016$Name=="Aaron Rodgers", ]$QBR,
NA, # only played 7 games
data2018[data2018$Name=="Aaron Rodgers", ]$QBR,
data2019[data2019$Name=="Aaron Rodgers", ]$QBR,
data2020[data2020$Name=="Aaron RodgersGB", ]$QBR
)

rodgers_vector
```


```{r create dataframe for plot}
# initiate
df <- data.frame(NFL = playoffs_qb_mean, Rodgers = rodgers_vector)

# mutate in difference
df <- df %>% mutate(Difference = Rodgers - NFL)

# mutate in year
df$Year <- 2015:2020

# mutate in link to headshot
good <- "C:/Users/Myles/OneDrive/Documents/GitHubThings/twitter/rodgers-happy-beard.png"
bad <- "C:/Users/Myles/OneDrive/Documents/GitHubThings/twitter/rodgers-helmet-sad.png"
df$headshots <- c(bad, good, good, bad, bad, good)

df
```


```{r}
# trying and connect groups
df$group1 <- c("a", "a", "b", "a", "a", "a")

# factor
df$group1 <- as.factor(df$group1)
```



```{r}
# plot
p1 <- ggplot(df, aes(x = Year, y = Difference, image=headshots)) + 
  annotate("segment", x = 2015, xend = 2016, y = -4, yend = 10, colour = "black") +
  annotate("segment", x = 2016, xend = 2018, y = 10, yend = -8.5, colour = "black") +
  annotate("segment", x = 2018, xend = 2019, y = -8.5, yend = -12.5, colour = "black") +
  annotate("segment", x = 2019, xend = 2020, y = -12.5, yend = 12, colour = "black") +
  ggimage::geom_image(size = 0.12) +
  #ylim(-15, 15) + 
  labs(title = "QBR: Aaron Rodgers vs. mean play of playoff QBs",
       subtitle = "Note: Rodgers did not play enough in 2017 to qualify for QBR rankings",
       x = NULL,
       y = "QBR\n Difference",
       caption = "**Data:** ESPN | **Figure:** @WisconsinStats") + 
  geom_hline(yintercept = 0, color = "black", size = 1) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10),
                     limits = c(-15, 15)) +
  theme_fivethirtyeight() +
  theme_classic() +
  theme_minimal() +
  theme(
    text = element_text(family = "Consolas"),
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold", size = 18),
    plot.subtitle = element_text(size = 11),
    plot.caption = element_markdown(size = 14),
    axis.text = element_text(size = 14, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold", angle = 0, vjust = 0.5),
    axis.title.x=element_blank()
   # axis.text.x=element_blank(),
    #axis.ticks.x=element_blank()
    ) +
  annotate(geom = "text", x = 2016.7, y = -5, label = "QBR <= 60", size = 5) + 
  annotate(geom = "text", x = 2018.2, y = 9, label = "QBR >= 72", size = 5)

p1

# in case this is needed
asp_ratio <- 1.618

ggsave(
  "rodgers-qbr-plot.png", p1, 
  # make the width equivalent to the aspect.ratio by multiplying * asp_ratio
  # not needed for this one!
  height = 10, width = 10 * 1, dpi = "retina"
  )
```


```{r get gt theme for 538 and espn}
# library
library(gt)

# espn
gt_theme_espn <- function(data, ...){
  data %>% 
    opt_all_caps()  %>%
    opt_table_font(
      font = list(
        google_font("Lato"),
        default_fonts()
      )
    )  %>% 
    opt_row_striping() %>% 
    tab_options(
      row.striping.background_color = "#fafafa",
      table_body.hlines.color = "#f6f7f7",
      source_notes.font.size = 12,
      table.font.size = 16,
      table.width = px(700),
      heading.align = "left",
      heading.title.font.size = 24,
      table.border.top.color = "transparent",
      table.border.top.width = px(3),
      data_row.padding = px(7),
      ...
    ) 
}

# 538
gt_theme_538 <- function(data,...) {
  data %>%
  opt_all_caps()  %>%
  opt_table_font(
    font = list(
      google_font("Chivo"),
      default_fonts()
    )
  ) %>%
    tab_style(
      style = cell_borders(
        sides = "bottom", color = "transparent", weight = px(2)
      ),
      locations = cells_body(
        columns = everything(),
        # This is a relatively sneaky way of changing the bottom border
        # Regardless of data size
        rows = nrow(data$`_data`)
      )
    )  %>% 
  tab_options(
    column_labels.background.color = "white",
    table.border.top.width = px(3),
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    column_labels.border.top.width = px(3),
    column_labels.border.top.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "black",
    data_row.padding = px(3),
    source_notes.font.size = 12,
    table.font.size = 16,
    heading.align = "left",
    ...
  ) 
}

```




```{r}
df %>%
  slice(1:2, 4:6) %>%
  select(Year, NFL:Difference) %>%
  gt() %>%
  gt_theme_538() %>%
  tab_spanner(
    label = "QBR",
    columns = c(NFL, Rodgers)
  ) %>%
  data_color(
    columns = c(Difference),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#ff2700", "#f8fcf8", "#44ab43")
    )
  )
```


```{r, eval=FALSE}
rgb(colorRamp(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 1))

colorRamp()

rgb
```


```{r, eval=FALSE}
colfunc <- colorRampPalette(c("darkgreen", "white", "red"))

plot(rep(1,10), col=colfunc(10), pch=20, cex=4)
```














