---
title: "BucksHeat2021"
author: "Myles Thomas"
date: "5/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(tidyverse)
library(dplyr)
library(tictoc)
library(espnscrapeR)
library(tidyverse)
library(ggtext)
library(adegenet)
library(ggplot2)
library(ggimage)
library(extrafont)
library(scales)
library(ggthemes)
```



```{r get gt theme for 538 and espn}
# library
library(gt)

# espn
gt_theme_espn <- function(data, ...){
  data %>% 
    opt_all_caps()  %>%
    opt_table_font(
      font = list(
        google_font("Lato"),
        default_fonts()
      )
    )  %>% 
    opt_row_striping() %>% 
    tab_options(
      row.striping.background_color = "#fafafa",
      table_body.hlines.color = "#f6f7f7",
      source_notes.font.size = 12,
      table.font.size = 16,
      table.width = px(700),
      heading.align = "left",
      heading.title.font.size = 24,
      table.border.top.color = "transparent",
      table.border.top.width = px(3),
      data_row.padding = px(7),
      ...
    ) 
}

# 538
gt_theme_538 <- function(data,...) {
  data %>%
  opt_all_caps()  %>%
  opt_table_font(
    font = list(
      google_font("Chivo"),
      default_fonts()
    )
  ) %>%
    tab_style(
      style = cell_borders(
        sides = "bottom", color = "transparent", weight = px(2)
      ),
      locations = cells_body(
        columns = everything(),
        # This is a relatively sneaky way of changing the bottom border
        # Regardless of data size
        rows = nrow(data$`_data`)
      )
    )  %>% 
  tab_options(
    column_labels.background.color = "white",
    table.border.top.width = px(3),
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    column_labels.border.top.width = px(3),
    column_labels.border.top.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "black",
    data_row.padding = px(3),
    source_notes.font.size = 12,
    table.font.size = 16,
    heading.align = "left",
    ...
  ) 
}

```




```{r}
library(readxl)
bucks5_24 <- read_excel("~/GitHubThings/all-files/bucks5-24.xlsx") ; bucks5_24

# grab columns
df <- bucks5_24 %>%
  select(Player, `eFG%`, ORtg:DRtg)

# turn into numeric
df$`eFG%`<- df$`eFG%` %>% as.numeric()
df$ORtg <- df$ORtg %>% as.numeric()
df$DRtg <- df$DRtg %>% as.numeric()

# mutate in difference
df <- df %>% mutate(NetRating = ORtg - DRtg)


data <- df[order(-df$NetRating), ]

data %>%
  gt() %>%
  gt_theme_538() %>%
  data_color(
    columns = c(`eFG%`),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#ff2700", "#f8fcf8", "#44ab43") # low number RED, middle=white, high number GREEN
    )
  ) %>%
  data_color(
    columns = c(ORtg),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#f8fcf8", "skyblue1", "darkblue") # low number WHITE, middle blend, high number DARK BLUE
    )
  ) %>%
  
  data_color(
    columns = c(DRtg),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#f8fcf8", "gray") 
    )
  ) %>%
    data_color(
    columns = c(NetRating),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#ff2700", "#f8fcf8", "#44ab43") # low number RED, middle=white, high number GREEN
    )
  ) %>%
  tab_spanner(
    label = "Scoring",
    columns = c(`eFG%`)
  ) %>%
  tab_spanner(
    label = "Efficiency",
    columns = c(ORtg:NetRating)
  ) %>%
  cols_label(NetRating = "Net Rating") %>%
  cols_label(ORtg = "Off.\n Rating") %>%
  cols_label(DRtg = "Def. \nRating") %>%
  tab_source_note(
    source_note = md("SOURCE: BasketballReference <br>TABLE: @WisconsinStats")
  ) %>%
  tab_header(title = md("**Milwaukee Bucks Playoff Efficiency**"),
             subtitle = md("Game 1 vs. Miami")) 
  

```

```{r}
lopez <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201572.png"
portis <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1626171.png"
middleton <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203114.png"
jrue <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201950.png"
pat <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1626192.png"
bryn <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627854.png"
giannis <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203507.png"
donte <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1628978.png"
pj <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/200782.png"

toupane <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1626253.png"
teague <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201952.png"
nwora <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1629670.png"
merrill <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1630241.png"
justin_j <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1628382.png"
diakite <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1629603.png"
bryant <- "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3129951.png"
thanasis <- "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203648.png"

bucks_logo <- "https://www.nba.com/bucks/sites/bucks/files/secondary-logo.png"

pngs <- c(lopez, portis, middleton, jrue, pat, bryn, giannis, donte, pj)

data$url <- pngs # add url for each headshot

data <- data %>%
  select(Player, url, `eFG%`:NetRating) ; data
```

```{r}
# add headshot to table
gt1 <- data %>%
  gt() %>%
  text_transform(
    locations = cells_body(c(url)),
    fn = function(x) {
      web_image(
        url = x,
        height = gt::px(30)
      )
    }
  ) %>%
  cols_label(
    url = "",
    Player = "Name",
    `eFG%` = "Effective FG%",
    ORtg = "Offensive Rating",
    DRtg = "Defensive Rating",
    NetRating = "Net Rating"
  ) %>%
  tab_source_note(
    source_note = md("SOURCE: BasketballReference <br>TABLE: @WisconsinStats")
  ) %>%
  tab_header(title = md("**Milwaukee Bucks Playoff Efficiency**"),
             subtitle = md("Game 1 vs. Miami")) %>%
  gt_theme_538() %>%
  data_color(
    columns = c(`eFG%`),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#ff2700", "#f8fcf8", "#44ab43") # low number RED, middle=white, high number GREEN
    )
  ) %>%
  data_color(
    columns = c(ORtg),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#f8fcf8", "skyblue1", "darkblue") # low number WHITE, middle blend, high number DARK BLUE
    )
  ) %>%
  
  data_color(
    columns = c(DRtg),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("gray", "#f8fcf8") 
    )
  ) %>%
    data_color(
    columns = c(NetRating),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#ff2700", "#f8fcf8", "#44ab43") # low number RED, middle=white, high number GREEN
    )
  ) %>%
  tab_spanner(
    label = "Scoring",
    columns = c(`eFG%`)
  ) %>%
  tab_spanner(
    label = "Efficiency",
    columns = c(ORtg:NetRating)
  ) ; gt1


  
# save
gt::gtsave(data = gt1,
           filename = "game1.png")
```




```{r game 2, eval=FALSE}
library(rvest)

url <- "https://www.nba.com/stats/lineups/advanced/?Season=2020-21&SeasonType=Playoffs&TeamID=1610612749&sort=NET_RATING&dir=1"

webpage <- read_html(url)

tbls <- html_nodes(webpage, "table")

head(tbls)


# tables
tables <- webpage %>%
        html_nodes("table") %>%
        .[1:2] %>%
        html_table(fill = TRUE)
```

```{r}
library(readxl)
bucks5_25 <- read_excel("~/GitHubThings/all-files/bucks5-25.xlsx")
bucks5_25

# add headshots
bucks5_25$heads <- c(bryn, giannis, middleton, nwora, pat, portis, merrill, 
                     jrue, lopez, toupane, donte, pj, bryant, diakite)

# mutate in net rating
bucks5_25 <- bucks5_25 %>% mutate("Diff" = `ORtg` - `DRtg`)

# grab columns
df <- bucks5_25 %>%
  select(Column1, heads, ORtg:Diff, `PTS▼`)

# rename columns
df <- df %>%
  rename("Name" = Column1,
         "Points per 100 possessions" = `PTS▼`,
         "Offensive Rating" = ORtg,
         "Defensive Rating" = DRtg,
         "Net Rating" = Diff)


# turn into numerics
df <- mutate_at(.tbl = df, .vars = c(names(df)[3:6]), .funs = as.numeric)

data <- df[order(-df$`Points per 100 possessions`), ] ; data
```

```{r}
# table
gt2 <- data %>%
  gt() %>%
  text_transform(
    locations = cells_body(c(heads)),
    fn = function(x) {
      web_image(
        url = x,
        height = gt::px(30)
      )
    }
  ) %>%
  tab_source_note(
    source_note = md("SOURCE: BasketballReference <br>TABLE: @WisconsinStats")
  ) %>%
  tab_header(title = md("**Playoffs Per 100 Possessions**"),
             subtitle = md("Games 1-2 vs. Miami")) %>%
  gt_theme_538() %>%
  data_color(
    columns = c(`Net Rating`),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#ff2700", "#f8fcf8", "#44ab43") # low number RED, middle=white, high number GREEN
    )
  ) %>%
  data_color(
    columns = c(`Offensive Rating`),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#f8fcf8", "skyblue1", "darkblue") # low number WHITE, middle blend, high number DARK BLUE
    )
  ) %>%
  
  data_color(
    columns = c(`Defensive Rating`),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("gray", "#f8fcf8") 
    )
  ) %>%
    data_color(
    columns = c(`Points per 100 possessions`),
    colors = scales::col_numeric(
      domain = NULL,
      palette = c("#f8fcf8", "#44ab43") # low number white, high number GREEN
    )
  ) %>%
  tab_spanner(
    label = "Points",
    columns = c(`Points per 100 possessions`)
  ) %>%
  tab_spanner(
    label = "Efficiency",
    columns = c(`Offensive Rating`:`Net Rating`)
  ) %>%
  cols_label(
    heads = ""
  ); gt1


  
# save
gt::gtsave(data = gt2,
           filename = "afterg2.png")
```

